# Generated by Django 2.2.16 on 2022-05-02 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220502_0440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='titles',
            new_name='title',
        ),
    ]
