# Generated by Django 2.2.16 on 2022-05-02 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20220502_0643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['year']},
        ),
    ]
